language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: RSwntzzExFEHSFcrCfYsegJHOlh09hrtuO9DeL4dVtRcfctIkTsz8PRe2PDs93XcRSVAwE4T7cgRpu5Z5VqgjayOhheDw4Wsl/Ow6RxGVw81GhaYt/IisYTkZqGMU9sYcJPinUDHFZ+vuYakRBhPlLdmdyRj0FwcMHmGtWPzV2amjolpmS+HYbYo9xRZbxKWWr1tUyZnKWhl195dPyzU9JkKmxLZ5bOu92oud+YADyUiQFBKMOq2u+zOnpoJzz5fjvJOqx0R6dsSYl4ad2QvoA7WUWvXBehp0rbCx6yMqL+OfY/mrYD1GjsKty3+UhOxdacQiBocKMdm1aWfSD5BFCYPtNcBi7YPm9bD4zuHxJK1RN5Y3PUWWL1gS8XFpBQyg7Wn+tGHEf05rZVPdM87VVDRDF/1VT0MUFKyt4fHfDssqNhUreSnrvY/TfA086SOjQY82+is/uPWFTn+NsQ1umvrU1+0b7MH6Cg7x4J8VZvMaGN2UTUUOQkYXYOKuDZ+iVYW7JrzxXLn8xLJOn/dXBEWR3oS5s9uHN+HV1JgIutin14vjcpBbq3WWrnhf3KAlxDvTX+QrRHjieo0q8yjG6z8U0GX36+6C3qB3SD0erQJRCG+aERq61OGNfrl6YGPEn3lOWk/8w/SM2G3A+s5FQ+RRXzBNyf6/WoxbRAZdvc=
  app: cow-capacitor-666